import type { AppLauncher, Hub } from '@/types';

export const DEFAULT_HUBS: Hub[] = [
  { id: 'news', name: 'News Hub', icon: '📰', searchQuery: 'latest world news today' },
  { id: 'ai', name: 'AI Hub', icon: '🤖', searchQuery: 'AI tools 2026' },
  { id: 'islamic', name: 'Islamic Hub', icon: '🕌', searchQuery: 'Islamic resources quran hadith' },
  { id: 'social', name: 'Social Hub', icon: '👥', searchQuery: 'social media platforms' },
  { id: 'general', name: 'General Hub', icon: '🌐', searchQuery: 'top websites 2026' },
  { id: 'tech', name: 'Tech Hub', icon: '💻', searchQuery: 'technology news programming' },
  { id: 'edu', name: 'Edu Hub', icon: '📚', searchQuery: 'online learning courses education' },
];

export const DEFAULT_LAUNCHERS: AppLauncher[] = [
  {
    id: 'youtube',
    name: 'YouTube',
    url: 'https://youtube.com',
    icon: '▶️',
    color: 'from-red-400 to-red-600',
    isDefault: true,
    category: 'Entertainment',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    url: 'https://web.whatsapp.com',
    icon: '💬',
    color: 'from-green-400 to-green-600',
    isDefault: true,
    category: 'Social',
  },
  {
    id: 'aistudio',
    name: 'AI Studio',
    url: 'https://aistudio.google.com',
    icon: '✨',
    color: 'from-purple-400 to-purple-600',
    isDefault: true,
    category: 'AI',
  },
  {
    id: 'google',
    name: 'Google',
    url: 'https://www.google.com',
    icon: '🔍',
    color: 'from-blue-400 to-blue-600',
    isDefault: true,
    category: 'Search',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    url: 'https://mail.google.com',
    icon: '📧',
    color: 'from-red-400 to-orange-500',
    isDefault: true,
    category: 'Productivity',
  },
  {
    id: 'twitter',
    name: 'Twitter / X',
    url: 'https://x.com',
    icon: '🐦',
    color: 'from-slate-600 to-slate-800',
    isDefault: true,
    category: 'Social',
  },
  {
    id: 'github',
    name: 'GitHub',
    url: 'https://github.com',
    icon: '💾',
    color: 'from-gray-600 to-gray-800',
    isDefault: true,
    category: 'Dev',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    url: 'https://www.reddit.com',
    icon: '🦊',
    color: 'from-orange-400 to-orange-600',
    isDefault: true,
    category: 'Social',
  },
  {
    id: 'media',
    name: 'Media Player',
    url: '__media__',
    icon: '🎬',
    color: 'from-blue-500 to-indigo-600',
    isDefault: true,
    category: 'Media',
  },
];

export const ICON_OPTIONS = ['🌐', '🔗', '📌', '⚡', '🎯', '💡', '📊', '🎨', '🛒', '📰', '🎵', '🏠', '🌍', '🔐', '💼', '🎮', '📷', '✈️', '🏋️', '💰'];

export const COLOR_OPTIONS = [
  { label: 'Blue', value: 'from-blue-400 to-blue-600' },
  { label: 'Purple', value: 'from-purple-400 to-purple-600' },
  { label: 'Green', value: 'from-green-400 to-green-600' },
  { label: 'Red', value: 'from-red-400 to-red-600' },
  { label: 'Orange', value: 'from-orange-400 to-orange-600' },
  { label: 'Pink', value: 'from-pink-400 to-pink-600' },
  { label: 'Teal', value: 'from-teal-400 to-teal-600' },
  { label: 'Indigo', value: 'from-indigo-400 to-indigo-600' },
  { label: 'Yellow', value: 'from-yellow-400 to-amber-500' },
  { label: 'Slate', value: 'from-slate-500 to-slate-700' },
];
